import os
import subprocess
import glob
from typing import List
from PIL import Image

class ImageExtractor:
    """
    Asset extractor that pulls high-definition pictures embedded inside PDF documents.
    Employs native pdfimages tool and discards low-resolution, small, or icon background images.
    """

    @staticmethod
    def extract(pdf_path: str, assets_dir: str) -> List[str]:
        """
        Runs pdfimages -png to extract embedded images, and filters out images smaller than 300x300 pixels.
        Returns a sorted list of the absolute filesystem paths to the saved images.
        """
        if not os.path.exists(pdf_path):
            raise FileNotFoundError(f"Source PDF not found for extraction: {pdf_path}")
        
        os.makedirs(assets_dir, exist_ok=True)
        # Prefix for output files generated by pdfimages
        prefix = os.path.join(assets_dir, "extracted_img")

        try:
            # subprocess.run pdfimages -png pdf_path prefix
            subprocess.run(
                ["pdfimages", "-png", pdf_path, prefix],
                check=True,
                capture_output=True
            )
        except Exception as e:
            # If pdfimages fails or is not available, we gracefully catch
            # (In some systems layout is different, but the requirement specifies running pdfimages -png)
            pass

        # Scan for generated image files in assets_dir
        image_pattern = os.path.join(assets_dir, "extracted_img-*.png")
        all_extracted_images = glob.glob(image_pattern)

        saved_image_paths = []

        for img_path in all_extracted_images:
            try:
                with Image.open(img_path) as img:
                    width, height = img.size
                    # Filter out small, spacer, or icon-like background graphics (under 300x300)
                    if width >= 300 and height >= 300:
                        saved_image_paths.append(img_path)
                    else:
                        # Clean up filtered images from disk immediately
                        os.remove(img_path)
            except Exception:
                # If image is corrupted or fail to open, purge it safely
                if os.path.exists(img_path):
                    try:
                        os.remove(img_path)
                    except OSError:
                        pass

        # Sort paths to keep natural reading sequence intact (e.g. 000, 001...)
        saved_image_paths.sort()
        return saved_image_paths
