import os
import subprocess
import glob
from typing import List
from PIL import Image

class ImageExtractor:
    """
    Asset extractor that pulls high-definition pictures embedded inside PDF documents.
    Employs native pdfimages tool and discards low-resolution, small, or icon background images.
    """

    @staticmethod
    def extract(pdf_path: str, assets_dir: str, page_count: int = 1) -> List[tuple[str, int]]:
        """
        Runs pdfimages -png to extract embedded images, and filters out images smaller than 300x300 pixels.
        Returns a sorted list of the absolute filesystem paths to the saved images.
        """
        if not os.path.exists(pdf_path):
            raise FileNotFoundError(f"Source PDF not found for extraction: {pdf_path}")
        
        os.makedirs(assets_dir, exist_ok=True)
        # Prefix for output files generated by pdfimages
        prefix = os.path.join(assets_dir, "extracted_img")

        saved_image_paths = []

        for page_num in range(1, page_count + 1):
            page_prefix = os.path.join(assets_dir, f"page{page_num}_img")
            try:
                subprocess.run(
                    ["pdfimages", "-png", "-f", str(page_num), "-l", str(page_num), pdf_path, page_prefix],
                    check=True,
                    capture_output=True
                )
            except FileNotFoundError:
                raise RuntimeError("pdfimages is not installed. Install poppler-utils.")
            except subprocess.CalledProcessError as e:
                raise RuntimeError(f"pdfimages failed on page {page_num}: {e.stderr.decode()}")

            pattern = os.path.join(assets_dir, f"page{page_num}_img-*.png")
            for img_path in sorted(glob.glob(pattern)):
                try:
                    with Image.open(img_path) as img:
                        w, h = img.size
                        if w >= 300 and h >= 300:
                            saved_image_paths.append((img_path, page_num))  # <-- tuple
                        else:
                            os.remove(img_path)
                except Exception:
                    if os.path.exists(img_path):
                        try:
                            os.remove(img_path)
                        except OSError:
                            pass

        return saved_image_paths
